version: '3'
services:
  db:
    image: postgres:14.5
    container_name: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  dbdata:
