version: '3'
services:
  db:
    image: postgres:14.5
    container_name: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b 0.0.0.0
  crond:
    build: .
    command: crond && bundle exec whenever --set 'env_path=/usr/local/bin' --update-crontab
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    restart: always

volumes:
  dbdata:
